apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskme-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskme-ui
  template:
    metadata:
      labels:
        app: taskme-ui
    spec:
      containers:
      - name: taskme-ui
        image: dvzpoc/taskmeui:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: ""
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
